services:
  - type: web
    name: interfone-backend
    env: node
    buildCommand: |
      npm install
      npx puppeteer install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production