services:
  - type: web
    name: interfone-backend
    env: node
    buildCommand: |
      bash install-chrome.sh
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
